# Generated by Django 3.2.7 on 2021-09-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shagai", "0004_contest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoloPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum16", models.IntegerField()),
                ("sum8", models.IntegerField()),
                ("sum4", models.IntegerField()),
                ("tulaa", models.IntegerField()),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shagai.contest"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shagai.player"
                    ),
                ),
            ],
        ),
    ]
