# Generated by Django 3.2.7 on 2021-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shagai", "0005_soloperformance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soloperformance",
            options={
                "ordering": ("contest", "player", "-sum16", "-sum8", "-sum4", "-tulaa")
            },
        ),
    ]
